dist: trusty
language: node_js
node_js:
- '7'
addons:
  ssh_known_hosts: $DEPLOY_SSH_HOST
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
deploy:
  skip_cleanup: true
  provider: script
  script: sshpass -p $DEPLOY_SSH_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST -t "$DEPLOY_SSH_PATH/sfs-deploy.sh"
  on:
    branch: release
before_install:
- npm install -g @angular/cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: test
      - script: npm run lint
      - script: npm run test:once
      - script: npm run e2e
    - stage: send test coverage report
      - script: cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage --token $CODACY_PROJECT_TOKEN
