dist: trusty
language: node_js
node_js:
- '7'
before_install:
- npm install -g @angular/cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      script:
       - npm run lint && npm run test:once
       - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage --token $CODACY_PROJECT_TOKEN
    - script: npm run e2e
    - stage: deploy
      addons:
        ssh_known_hosts: $DEPLOY_SSH_HOST
        apt:
          packages:
            - sshpass
      before_install: echo 'Skip...'
      install: echo 'Skip...'
      script: echo 'Deploying...'
      deploy:
        skip_cleanup: true
        provider: script
        script: sshpass -p $DEPLOY_SSH_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST -t "$DEPLOY_SSH_PATH/sfs-deploy.sh"
        on:
          tags: true
